// +build routerrpc

// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: routerrpc/router.proto
package lndmobile

import (
	"context"
	"net"
	"time"

	"google.golang.org/grpc"

	"github.com/golang/protobuf/proto"

	"github.com/lightningnetwork/lnd/lnrpc/routerrpc"
)

func getRouterConn() (*grpc.ClientConn, func(), error) {
	conn, err := lightningLis.Dial()
	if err != nil {
		return nil, nil, err
	}

	clientConn, err := grpc.Dial("",
		grpc.WithDialer(func(target string,
			timeout time.Duration) (net.Conn, error) {
			return conn, nil
		}),
		grpc.WithInsecure(),
		grpc.WithBackoffMaxDelay(10*time.Second),
	)
	if err != nil {
		conn.Close()
		return nil, nil, err
	}

	close := func() {
		conn.Close()
	}

	return clientConn, close, nil
}

// getRouterClient returns a client connection to the server listening
// on lis.
func getRouterClient() (routerrpc.RouterClient, func(), error) {
	clientConn, close, err := getRouterConn()
	if err != nil {
		return nil, nil, err
	}
	client := routerrpc.NewRouterClient(clientConn)
	return client, close, nil
}

// SendPayment attempts to route a payment described by the passed
// PaymentRequest to the final destination. The call returns a stream of
// payment status updates.
//
// NOTE: This method produces a stream of responses, and the receive stream can
// be called zero or more times. After EOF error is returned, no more responses
// will be produced.
func SendPayment(msg []byte, rStream RecvStream) {
	s := &readStreamHandler{
		newProto: func() proto.Message {
			return &routerrpc.SendPaymentRequest{}
		},
		recvStream: func(ctx context.Context,
			req proto.Message) (*receiver, func(), error) {

			// Get the gRPC client.
			client, close, err := getRouterClient()
			if err != nil {
				return nil, nil, err
			}

			r := req.(*routerrpc.SendPaymentRequest)
			stream, err := client.SendPayment(ctx, r)
			if err != nil {
				close()
				return nil, nil, err
			}
			return &receiver{
				recv: func() (proto.Message, error) {
					return stream.Recv()
				},
			}, close, nil
		},
	}
	s.start(msg, rStream)
}

// TrackPayment returns an update stream for the payment identified by the
// payment hash.
//
// NOTE: This method produces a stream of responses, and the receive stream can
// be called zero or more times. After EOF error is returned, no more responses
// will be produced.
func TrackPayment(msg []byte, rStream RecvStream) {
	s := &readStreamHandler{
		newProto: func() proto.Message {
			return &routerrpc.TrackPaymentRequest{}
		},
		recvStream: func(ctx context.Context,
			req proto.Message) (*receiver, func(), error) {

			// Get the gRPC client.
			client, close, err := getRouterClient()
			if err != nil {
				return nil, nil, err
			}

			r := req.(*routerrpc.TrackPaymentRequest)
			stream, err := client.TrackPayment(ctx, r)
			if err != nil {
				close()
				return nil, nil, err
			}
			return &receiver{
				recv: func() (proto.Message, error) {
					return stream.Recv()
				},
			}, close, nil
		},
	}
	s.start(msg, rStream)
}

// EstimateRouteFee allows callers to obtain a lower bound w.r.t how much it
// may cost to send an HTLC to the target end destination.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func EstimateRouteFee(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &routerrpc.RouteFeeRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, close, err := getRouterClient()
			if err != nil {
				return nil, err
			}
			defer close()

			r := req.(*routerrpc.RouteFeeRequest)
			return client.EstimateRouteFee(ctx, r)
		},
	}
	s.start(msg, callback)
}

// SendToRoute attempts to make a payment via the specified route. This method
// differs from SendPayment in that it allows users to specify a full route
// manually. This can be used for things like rebalancing, and atomic swaps.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func SendToRoute(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &routerrpc.SendToRouteRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, close, err := getRouterClient()
			if err != nil {
				return nil, err
			}
			defer close()

			r := req.(*routerrpc.SendToRouteRequest)
			return client.SendToRoute(ctx, r)
		},
	}
	s.start(msg, callback)
}

// ResetMissionControl clears all mission control state and starts with a clean
// slate.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func ResetMissionControl(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &routerrpc.ResetMissionControlRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, close, err := getRouterClient()
			if err != nil {
				return nil, err
			}
			defer close()

			r := req.(*routerrpc.ResetMissionControlRequest)
			return client.ResetMissionControl(ctx, r)
		},
	}
	s.start(msg, callback)
}

// QueryMissionControl exposes the internal mission control state to callers.
// It is a development feature.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func QueryMissionControl(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &routerrpc.QueryMissionControlRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, close, err := getRouterClient()
			if err != nil {
				return nil, err
			}
			defer close()

			r := req.(*routerrpc.QueryMissionControlRequest)
			return client.QueryMissionControl(ctx, r)
		},
	}
	s.start(msg, callback)
}
