// Code generated by falafel 0.3. DO NOT EDIT.
// source: watchtowerrpc/watchtower.proto

// +build watchtowerrpc

package lndmobile

import (
	"context"
	"net"
	"time"

	"google.golang.org/grpc"

	"github.com/golang/protobuf/proto"

	"github.com/lightningnetwork/lnd/lnrpc/watchtowerrpc"
)

func getWatchtowerConn() (*grpc.ClientConn, func(), error) {
	conn, err := lightningLis.Dial()
	if err != nil {
		return nil, nil, err
	}

	clientConn, err := grpc.Dial("",
		grpc.WithDialer(func(target string,
			timeout time.Duration) (net.Conn, error) {
			return conn, nil
		}),
		grpc.WithInsecure(),
		grpc.WithBackoffMaxDelay(10*time.Second),
	)
	if err != nil {
		conn.Close()
		return nil, nil, err
	}

	close := func() {
		conn.Close()
	}

	return clientConn, close, nil
}

// getWatchtowerClient returns a client connection to the server listening
// on lis.
func getWatchtowerClient() (watchtowerrpc.WatchtowerClient, func(), error) {
	clientConn, close, err := getWatchtowerConn()
	if err != nil {
		return nil, nil, err
	}
	client := watchtowerrpc.NewWatchtowerClient(clientConn)
	return client, close, nil
}

// GetInfo returns general information concerning the companion watchtower
// including it's public key and URIs where the server is currently
// listening for clients.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func GetInfo(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &watchtowerrpc.GetInfoRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, close, err := getWatchtowerClient()
			if err != nil {
				return nil, err
			}
			defer close()

			r := req.(*watchtowerrpc.GetInfoRequest)
			return client.GetInfo(ctx, r)
		},
	}
	s.start(msg, callback)
}
